name: jseen
description: Json Tree Viewer.
version: 1.0.0
homepage: https://github.com/jinyus/jseen

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_easy_treeview: ^1.0.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
